[Unit]
# Add setup-storage-bind-mounts dependency at cleanup; omitted from base unit because
# setup-storage-bind-mounts does not exist during build VM (storage volume not attached).
Requires=setup-storage-bind-mounts.service
After=setup-storage-bind-mounts.service
