"""Post-launch host tuning: CPU power and QEMU vCPU thread pinning."""

from __future__ import annotations

import glob
import os
import re
import subprocess
import time

# Written by tune_host_cpu_power(); consumed by restore_host_tuning().
# Stored under /var/lib/chutes/ so it survives /tmp cleanups while the VM is running.
RESTORE_SCRIPT = "/var/lib/chutes/tdx-host-tuning-restore.sh"


def expand_cpulist(raw: str) -> list[int]:
    """Expand a sysfs cpulist string (e.g. '0-47,96-143') to CPU IDs."""
    cpus: list[int] = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            lo, hi = part.split("-", 1)
            cpus.extend(range(int(lo), int(hi) + 1))
        else:
            cpus.append(int(part))
    return [cpu for cpu in cpus if cpu != 0]


def host_node_cpus(host_node: int) -> list[int]:
    """Return logical CPUs on a host NUMA node, excluding CPU 0."""
    path = f"/sys/devices/system/node/node{host_node}/cpulist"
    try:
        with open(path) as f:
            return expand_cpulist(f.read())
    except OSError:
        return []


def _run_root(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    if os.geteuid() == 0:
        return subprocess.run(cmd, **kwargs)
    return subprocess.run(["sudo", *cmd], **kwargs)


def _write_root(path: str, value: str) -> None:
    if os.geteuid() == 0:
        with open(path, "w") as f:
            f.write(value)
        return
    subprocess.run(
        ["sudo", "tee", path],
        input=value,
        text=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )


def tune_host_cpu_power() -> None:
    """Set performance governor, enable turbo, and disable C-states (TDX perf §3.0).

    Snapshots current values to RESTORE_SCRIPT before writing so the host can
    be returned to its previous state when the VM stops. If a restore script
    already exists the host is already tuned — skip snapshotting to avoid
    overwriting the original saved state with already-tuned values.
    """
    print("Host CPU performance tuning...")

    already_tuned = os.path.isfile(RESTORE_SCRIPT)
    if already_tuned:
        print(f"  Host already tuned (restore script exists at {RESTORE_SCRIPT}), reapplying settings only.")

    restore_cmds: list[str] = [
        "#!/usr/bin/env bash",
        "# Restore host CPU settings captured before TDX VM launch.",
        "# Generated by post_launch.tune_host_cpu_power() — do not edit.",
        "",
    ]

    for gov_file in sorted(glob.glob("/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor")):
        if not already_tuned:
            try:
                with open(gov_file) as f:
                    saved = f.read().strip()
                restore_cmds.append(f"echo {saved} | sudo tee {gov_file} > /dev/null")
            except OSError:
                pass
        _write_root(gov_file, "performance")

    for epp_file in sorted(glob.glob("/sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference")):
        if not already_tuned:
            try:
                with open(epp_file) as f:
                    saved = f.read().strip()
                restore_cmds.append(f"echo {saved} | sudo tee {epp_file} > /dev/null")
            except OSError:
                pass
        _write_root(epp_file, "performance")

    if glob.glob("/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference"):
        print("  CPU governor + EPP: performance")
    else:
        print("  CPU governor: performance")

    no_turbo = "/sys/devices/system/cpu/intel_pstate/no_turbo"
    if os.path.isfile(no_turbo):
        if not already_tuned:
            try:
                with open(no_turbo) as f:
                    saved = f.read().strip()
                restore_cmds.append(f"echo {saved} | sudo tee {no_turbo} > /dev/null")
            except OSError:
                pass
        _write_root(no_turbo, "0")
        print("  Turbo Boost: enabled")

    for idle_file in sorted(glob.glob("/sys/devices/system/cpu/cpu*/cpuidle/state*/disable")):
        if not already_tuned:
            try:
                with open(idle_file) as f:
                    saved = f.read().strip()
                restore_cmds.append(f"echo {saved} | sudo tee {idle_file} > /dev/null")
            except OSError:
                pass
        _write_root(idle_file, "1")
    print("  C-states: disabled at runtime")

    if not already_tuned:
        restore_cmds += [
            "",
            "echo 'Host CPU settings restored.'",
            f"rm -f {RESTORE_SCRIPT}",
        ]
        try:
            os.makedirs(os.path.dirname(RESTORE_SCRIPT), exist_ok=True)
            with open(RESTORE_SCRIPT, "w") as f:
                f.write("\n".join(restore_cmds) + "\n")
            os.chmod(RESTORE_SCRIPT, 0o755)
            print(f"  Restore script: {RESTORE_SCRIPT}")
        except OSError as exc:
            print(f"  Warning: could not write restore script: {exc}")


def _read_pidfile(pidfile: str) -> int | None:
    try:
        with open(pidfile) as f:
            return int(f.read().strip())
    except (OSError, ValueError):
        return None


def find_qemu_pid(*, pidfile: str) -> int | None:
    """Resolve QEMU PID from the pidfile written at launch.

    Returns None if the pidfile is missing, unreadable, or the process is
    no longer running. Intentionally does not fall back to pgrep to avoid
    accidentally pinning threads of an unrelated process.
    """
    pid = _read_pidfile(pidfile)
    if pid is not None and os.path.exists(f"/proc/{pid}"):
        return pid
    return None


def _vcpu_thread_ids(pid: int) -> list[tuple[int, int]]:
    """Return (vcpu_index, thread_id) pairs sorted by vcpu index."""
    result = subprocess.run(
        ["ps", "-T", "-p", str(pid)],
        capture_output=True,
        text=True,
        check=False,
    )
    threads: list[tuple[int, int]] = []
    for line in result.stdout.splitlines():
        match = re.search(r"^\s*\d+\s+(\d+).*\bCPU (\d+)/KVM\b", line)
        if match:
            threads.append((int(match.group(2)), int(match.group(1))))
    threads.sort(key=lambda item: item[0])
    return threads


def _vcpu_thread_ids_wchan_fallback(pid: int) -> list[int]:
    """Fallback: threads with wchan '0' (KVM vCPU run loop)."""
    tids: list[int] = []
    task_dir = f"/proc/{pid}/task"
    try:
        for tid_name in os.listdir(task_dir):
            wchan_path = f"{task_dir}/{tid_name}/wchan"
            try:
                with open(wchan_path) as f:
                    if f.read().strip() == "0":
                        tids.append(int(tid_name))
            except OSError:
                continue
    except OSError:
        return []
    return sorted(tids)


def _iothread_ids(pid: int) -> list[int]:
    result = subprocess.run(
        ["ps", "-T", "-p", str(pid)],
        capture_output=True,
        text=True,
        check=False,
    )
    tids: list[int] = []
    for line in result.stdout.splitlines():
        match = re.search(r"^\s*\d+\s+(\d+).*iothread", line)
        if match:
            tids.append(int(match.group(1)))
    return tids


def pin_qemu_threads(
    pid: int,
    *,
    vcpus_total: int,
    host_nodes: list[int],
) -> None:
    """Pin QEMU vCPU (and IOthread) threads to host NUMA-local CPUs."""
    if not host_nodes:
        print("  Warning: no host NUMA nodes for thread pinning")
        return

    num_guest_nodes = len(host_nodes)
    vcpus_per_node = vcpus_total // num_guest_nodes
    node_cpus = {node: host_node_cpus(node) for node in host_nodes}

    vcpu_threads = _vcpu_thread_ids(pid)
    if not vcpu_threads:
        print("  Falling back to wchan-based vCPU detection...")
        fallback_tids = _vcpu_thread_ids_wchan_fallback(pid)
        vcpu_threads = list(enumerate(fallback_tids))

    pinned = 0
    for vcpu_id, tid in vcpu_threads:
        guest_node = vcpu_id // vcpus_per_node
        if guest_node >= num_guest_nodes:
            guest_node = num_guest_nodes - 1
        host_node = host_nodes[guest_node]
        cpus = node_cpus.get(host_node, [])
        if not cpus:
            continue
        target_cpu = cpus[vcpu_id % len(cpus)]
        result = _run_root(
            ["taskset", "-pc", str(target_cpu), str(tid)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode == 0:
            pinned += 1

    print(
        f"  Pinned {pinned} vCPU thread(s) across {num_guest_nodes} NUMA nodes "
        f"({vcpus_per_node} vCPUs/node, avoiding CPU0)"
    )

    iothread_tids = _iothread_ids(pid)
    if not iothread_tids:
        return

    node0_cpus = node_cpus.get(host_nodes[0], [])
    if not node0_cpus:
        return

    iot_start = max(0, len(node0_cpus) - len(iothread_tids) - 1)
    iot_pinned = 0
    for iot_idx, tid in enumerate(iothread_tids):
        target_cpu = node0_cpus[iot_start + iot_idx]
        result = _run_root(
            ["taskset", "-pc", str(target_cpu), str(tid)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode == 0:
            iot_pinned += 1
    print(f"  Pinned {iot_pinned} IOthread(s) to dedicated pCPUs")


def restore_host_tuning() -> None:
    """Run the restore script emitted by tune_host_cpu_power(), if present."""
    if not os.path.isfile(RESTORE_SCRIPT):
        return
    print("Restoring host CPU settings...")
    result = subprocess.run([RESTORE_SCRIPT], check=False)
    if result.returncode != 0:
        print(f"  Warning: restore script exited {result.returncode}")


def apply_post_launch_tuning(
    *,
    pidfile: str,
    vcpus_total: int,
    host_nodes: list[int],
    pin_threads: bool,
    tune_cpu: bool = False,
) -> None:
    """Apply host CPU tuning and optional QEMU thread pinning after daemonized launch.

    tune_cpu controls the aggressive host-wide changes (governor, C-states, turbo).
    pin_threads controls QEMU vCPU thread → NUMA-node affinity, which is always
    scoped to QEMU's own threads and reverts automatically when the process exits.
    """
    if tune_cpu:
        tune_host_cpu_power()
    if not pin_threads:
        return

    print("Pinning vCPU threads to host NUMA nodes...")
    time.sleep(3)
    pid = find_qemu_pid(pidfile=pidfile)
    if pid is None:
        print("  Warning: could not find QEMU PID for thread pinning")
        return
    pin_qemu_threads(pid, vcpus_total=vcpus_total, host_nodes=host_nodes)
