#!/usr/bin/env bash
# setup-chutes-cvm.sh — install the `chutes-cvm` CLI on a host.
#
# chutes-cvm is a real Python package (src/chutes-cvm, import `chutes_cvm`,
# published to PyPI). This installs it into a dedicated venv and drops a
# `chutes-cvm` shim on PATH. Idempotent and self-contained — a miner can run it
# directly (no Ansible), and Ansible host-setup can `command:` the same script.
#
#   sudo host-tools/scripts/provision/setup-chutes-cvm.sh
#
# By default it installs from this checkout (src/chutes-cvm); set CHUTES_CVM_PYPI=1
# to install the published package from PyPI instead (no checkout needed).
#
# Overridable via env: CHUTES_CVM_VENV (default /opt/chutes-cvm/venv),
# CHUTES_CVM_BIN (default /usr/local/bin), CHUTES_CVM_PYPI (default unset -> checkout),
# CHUTES_CVM_VERSION (PyPI version spec when CHUTES_CVM_PYPI=1). The defaults need
# root; point them at a user-writable path to run without sudo.
set -euo pipefail

# This script lives at host-tools/scripts/provision/. The package source is at
# <repo>/src/chutes-cvm; the CLI's bash helpers (quick-launch.sh, discover-profile.sh,
# devices/reset-gpus.sh, …) are bundled inside the package (chutes_cvm/scripts) and
# resolve package-relative, so no scripts dir needs to be pointed at here.
PROVISION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "$PROVISION_DIR/.." && pwd)"                 # host-tools/scripts
REPO_ROOT="$(cd "$SCRIPTS_DIR/../.." && pwd)"                  # repo root
PKG_DIR="$REPO_ROOT/src/chutes-cvm"

VENV_DIR="${CHUTES_CVM_VENV:-/opt/chutes-cvm/venv}"
BIN_DIR="${CHUTES_CVM_BIN:-/usr/local/bin}"
SHIM="$BIN_DIR/chutes-cvm"

log() { printf '  %s\n' "$*"; }

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v python3 >/dev/null 2>&1 || {
    echo "ERROR: python3 not found. Install python3 (and python3-venv) first." >&2
    exit 1
}
if ! python3 -c 'import ensurepip' >/dev/null 2>&1; then
    echo "ERROR: python3 venv support missing. Install it: sudo apt-get install -y python3-venv" >&2
    exit 1
fi

# ── Virtualenv + install ──────────────────────────────────────────────────────
log "venv: $VENV_DIR"
mkdir -p "$(dirname "$VENV_DIR")"
python3 -m venv "$VENV_DIR"          # reuses an existing venv without clobbering it
"$VENV_DIR/bin/python3" -m pip install --quiet --upgrade pip

if [ "${CHUTES_CVM_PYPI:-}" = "1" ]; then
    log "install: chutes-cvm${CHUTES_CVM_VERSION:+==$CHUTES_CVM_VERSION} (PyPI)"
    "$VENV_DIR/bin/python3" -m pip install --quiet "chutes-cvm${CHUTES_CVM_VERSION:+==$CHUTES_CVM_VERSION}"
else
    [ -f "$PKG_DIR/pyproject.toml" ] || {
        echo "ERROR: package source not found at $PKG_DIR. Run from a checkout, or set CHUTES_CVM_PYPI=1." >&2
        exit 1
    }
    log "install: $PKG_DIR (checkout, editable)"
    "$VENV_DIR/bin/python3" -m pip install --quiet -e "$PKG_DIR"
fi

# ── chutes-cvm shim → the venv's console script ────────────────────────────────
# The CLI's bash helpers are bundled in the package and resolve package-relative, so
# the shim just execs the console script. Firmware and the GPU-tools wheel stay
# external (checkout-relative by default); override via CHUTES_CVM_FIRMWARE_DIR /
# CHUTES_CVM_GPU_TOOLS_DIR for a PyPI install with no checkout.
log "shim: $SHIM"
mkdir -p "$BIN_DIR"
cat > "$SHIM" <<EOF
#!/bin/sh
# chutes-cvm — generated by setup-chutes-cvm.sh.
exec "$VENV_DIR/bin/chutes-cvm" "\$@"
EOF
chmod +x "$SHIM"

echo "Installed chutes-cvm → $SHIM"
echo "Try: chutes-cvm verify-host"
