#!/usr/bin/env bash
# setup-chutes-cvm.sh — bootstrap the `chutes-cvm` CLI on a host.
#
# Idempotent and self-contained: creates/refreshes a venv with the CLI's current deps
# and installs the `chutes-cvm` shim that runs it against THIS repo checkout. Designed to
# be the single source of truth for CLI setup — a miner can run it directly (no Ansible
# needed), and Ansible host-setup can `command:` the same script.
#
#   sudo host-tools/scripts/provision/setup-chutes-cvm.sh
#
# Overridable via env: CHUTES_CVM_VENV (default /opt/chutes-cvm/venv),
# CHUTES_CVM_BIN (default /usr/local/bin). The defaults need root; point them at a
# user-writable path to run without sudo.
set -euo pipefail

# This script lives at host-tools/scripts/provision/, so the scripts/ dir holding the
# chutes.guest package is one level up.
PROVISION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "$PROVISION_DIR/.." && pwd)"

VENV_DIR="${CHUTES_CVM_VENV:-/opt/chutes-cvm/venv}"
BIN_DIR="${CHUTES_CVM_BIN:-/usr/local/bin}"
SHIM="$BIN_DIR/chutes-cvm"

log() { printf '  %s\n' "$*"; }

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v python3 >/dev/null 2>&1 || {
    echo "ERROR: python3 not found. Install python3 (and python3-venv) first." >&2
    exit 1
}
if ! python3 -c 'import ensurepip' >/dev/null 2>&1; then
    echo "ERROR: python3 venv support missing. Install it: sudo apt-get install -y python3-venv" >&2
    exit 1
fi

# ── Virtualenv (deps for config-driven commands; verify-host is pure stdlib) ──
log "venv: $VENV_DIR"
mkdir -p "$(dirname "$VENV_DIR")"
python3 -m venv "$VENV_DIR"          # reuses an existing venv without clobbering it
"$VENV_DIR/bin/python3" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python3" -m pip install --quiet pyyaml jsonschema

# ── chutes-cvm shim → the CLI, with this checkout's scripts/ on PYTHONPATH ──────
log "shim: $SHIM"
mkdir -p "$BIN_DIR"
cat > "$SHIM" <<EOF
#!/bin/sh
# chutes-cvm — generated by setup-chutes-cvm.sh. Runs the CLI from:
#   $SCRIPTS_DIR
# Re-run setup-chutes-cvm.sh from a different checkout to repoint it.
export PYTHONPATH="$SCRIPTS_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$VENV_DIR/bin/python3" -m chutes.guest.cli "\$@"
EOF
chmod +x "$SHIM"

echo "Installed chutes-cvm → $SHIM"
echo "Try: chutes-cvm verify-host"
