#!/usr/bin/env python3
"""
Generate the hash-pinned requirements file the guest image installs into /opt/sek8s/venv.

The guest venv is measured into RTMR3, so its contents must be byte-reproducible: the same
repo state must always install the same bytes. Resolving from pyproject.toml caret ranges
cannot do that -- it picks up whatever the index serves on build day. This emits exact
versions plus every artifact hash from poetry.lock, so pip installs one specific set of
bytes or fails.

Only the transitive closure of the guest packages is emitted. Today that happens to equal
the whole "main" group minus the workspace path dependencies, but it is computed rather
than assumed so the guest does not silently inherit a dependency added for some other
package in the workspace.

Workspace path dependencies (sek8s, sek8s-common, ...) are skipped: editable installs
cannot be hash-checked, so install-sek8s.yml installs them separately with --no-deps.

Usage:
    python generate_guest_requirements.py          # write the requirements file
    python generate_guest_requirements.py --check  # exit 1 if the committed file is stale
"""
import argparse
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_PATH = REPO_ROOT / "poetry.lock"
OUTPUT_PATH = (
    REPO_ROOT / "ansible" / "guest" / "roles" / "sek8s" / "files" / "guest-requirements.txt"
)

# Packages installed into the guest venv; their dependency closure is what gets pinned.
GUEST_PROJECTS = ("src/sek8s", "src/sek8s-common")

# Lock sources that are not PyPI artifacts and so carry no usable hash.
NON_INDEX_SOURCES = {"directory", "file", "url", "git"}

HEADER = """\
# Generated by scripts/generate_guest_requirements.py -- DO NOT EDIT BY HAND.
#
# Exact versions and artifact hashes for the guest venv (/opt/sek8s/venv), derived from
# poetry.lock. The venv is measured into RTMR3, so these pins are what make the image
# byte-reproducible; a substituted artifact fails the build instead of silently changing
# the measurement.
#
# Regenerate with: make guest-requirements
"""


def normalize(name: str) -> str:
    """PEP 503 style normalization, enough for lock/pyproject cross-referencing."""
    return name.lower().replace("_", "-").replace(".", "-")


def load_lock(lock_path: Path, group: str = "main") -> dict[str, dict]:
    """Map normalized package name -> lock entry, restricted to one dependency group.

    Restricting here is what keeps the walk honest: poetry has already resolved any
    requested extras into the group, so anything outside it is a dev/optional package the
    guest never installs.
    """
    data = tomllib.loads(lock_path.read_text())
    return {
        normalize(pkg["name"]): pkg
        for pkg in data.get("package", [])
        if group in pkg.get("groups", ["main"])
    }


def direct_dependencies(pyproject: Path) -> set[str]:
    """Non-path runtime dependencies declared by a project."""
    data = tomllib.loads(pyproject.read_text())
    declared = data["tool"]["poetry"]["dependencies"]
    names = set()
    for name, spec in declared.items():
        if name == "python":
            continue
        # Workspace siblings are installed separately; their own deps are pulled in below.
        if isinstance(spec, dict) and ("path" in spec or "url" in spec or "git" in spec):
            continue
        names.add(normalize(name))
    return names


def dependency_names(entry: dict) -> set[str]:
    """Every package name an entry depends on.

    ``[package.extras]`` is deliberately not walked: it lists a package's *optional* deps
    (docs, test suites), which are only installed when an extra is requested. Poetry has
    already folded any extra the workspace actually asks for into the locked group, so
    walking extras here would drag in things like sphinx and torch.
    """
    return {normalize(name) for name in entry.get("dependencies", {})}


def resolve_closure(roots: set[str], lock: dict[str, dict]) -> tuple[set[str], set[str]]:
    """Walk the lock from ``roots``. Returns (resolved names, names absent from the lock)."""
    seen: set[str] = set()
    missing: set[str] = set()
    stack = sorted(roots)
    while stack:
        name = stack.pop()
        if name in seen or name in missing:
            continue
        entry = lock.get(name)
        if entry is None:
            missing.add(name)
            continue
        seen.add(name)
        stack.extend(sorted(dependency_names(entry)))
    return seen, missing


def marker_for(entry: dict, group: str = "main") -> str | None:
    """Environment marker for ``entry``.

    Poetry writes ``markers`` as either a plain string or a table keyed by dependency
    group; a group absent from the table carries no marker for us.
    """
    markers = entry.get("markers")
    if isinstance(markers, dict):
        return markers.get(group)
    return markers


def render(names: set[str], lock: dict[str, dict]) -> str:
    """Render pinned requirements, sorted so the output is stable across runs."""
    blocks = [HEADER]
    for name in sorted(names):
        entry = lock[name]
        if entry.get("source", {}).get("type") in NON_INDEX_SOURCES:
            continue

        spec = f"{entry['name']}=={entry['version']}"
        marker = marker_for(entry)
        if marker:
            spec += f" ; {marker}"

        hashes = sorted(
            f["hash"] for f in entry.get("files", []) if f.get("hash", "").startswith("sha256:")
        )
        if not hashes:
            raise SystemExit(
                f"{entry['name']} {entry['version']} has no sha256 hashes in the lock; "
                "cannot pin it for a hash-checked install"
            )

        lines = [f"{spec} \\"]
        lines += [f"    --hash={digest} \\" for digest in hashes[:-1]]
        lines.append(f"    --hash={hashes[-1]}")
        blocks.append("\n".join(lines))

    return "\n".join(blocks) + "\n"


def build() -> str:
    lock = load_lock(LOCK_PATH)

    roots: set[str] = set()
    for project in GUEST_PROJECTS:
        roots |= direct_dependencies(REPO_ROOT / project / "pyproject.toml")

    resolved, missing = resolve_closure(roots, lock)
    if missing:
        raise SystemExit(
            "dependencies absent from poetry.lock (is the lock stale?): "
            + ", ".join(sorted(missing))
        )
    return render(resolved, lock)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed file differs from freshly generated output",
    )
    args = parser.parse_args()

    content = build()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} is missing; run: make guest-requirements", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text() != content:
            print(
                f"{OUTPUT_PATH} is out of date with poetry.lock; run: make guest-requirements",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content)
    count = sum(1 for line in content.splitlines() if line and not line.startswith((" ", "#")))
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({count} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
